version: '3.7'

services:
  consul:
    image: consul:1.14.5
    container_name: consul_dev
    restart: always
    ports:
      - "8500:8500"
    networks:
      - vehicles_networks

  db:
    container_name: vehicles_mysql
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    volumes:
      - vehicles_db:/var/lib/mysql:rw
      - ./scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql  # Uncommented
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=vehicles_db
      - MYSQL_USER=vehicles_user
      - MYSQL_PASSWORD=12345678
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    tty: true
    networks:
      - vehicles_networks

  redis:
    image: 'bitnami/redis:6.0.9'
    container_name: redis_dev
    restart: always
    ports:
      - "6380:6379"  # Changed port to avoid conflicts
    environment:
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=password123
    volumes:
      - vehicles_cache:/bitnami/redis/data:rw
    networks:
      - vehicles_networks

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vehicles_networks  # Added network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - vehicles_networks  # Added network

  vehicles:
    container_name: vehicles
    build:
      context: .
    ports:
      - "8080:8080"
    command: serve  # make `serve` into `seed` or `seed --truncate=true` if anyone want to run the seeder
    volumes:
      - ./:/project
    environment:
      - CONSUL_URL=http://consul_dev:8500
      - CONSUL_PATH=vehicles
      - DB_HOST=db
      - DB_USER=vehicles_user
      - DB_PASSWORD=12345678
      - DB_NAME=vehicles_db
      - REDIS_HOST=redis_dev
      - REDIS_PASSWORD=password123
      - MONGO_URI=mongodb://admin:password@mongo_db:27017
    tty: true
    depends_on:
      - mongo
      - consul
      - db
      - redis
    networks:
      - vehicles_networks
    restart: on-failure  # Moved restart policy here

networks:
  vehicles_networks:
    name: vehicles_networks
    driver: bridge

volumes:
  mongo_data:
  vehicles_db:
    name: vehicles-db-data
  vehicles_cache:
    name: vehicles-cache-data