version: '3.7'

services:
  consul:
    image: consul:1.14.5
    container_name: consul_dev
    restart: always
    ports:
      - "8500:8500"
    networks:
      - vehicles_networks

  vehicles:
    container_name: vehicles
    build:
      context: .
    ports:
      - "8080:8080"
    command: serve  # make `serve` into `seed` or `seed --truncate=true` if anyone want to run the seeder
    volumes:
      - ./:/project
    environment:
      - CONSUL_URL=http://consul_dev:8500
      - CONSUL_PATH=vehicles
    tty: true
    depends_on:
      - consul
    networks:
      - vehicles_networks
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  vehicles_networks:
    name: vehicles_networks
    driver: bridge

#volumes:
#  vehicles_db:
#    name: vehicles-db-data
#  vehicles_cache:
#    name: vehicles-cache-data